services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/custom/data/postgresql/data
      - ./pg_hba.conf:/custom/data/postgresql/data/pg_hba.conf
      - ./init:/docker-entrypoint-initdb.d
      -
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    env_file: ".env"

  redis:
    image: redis:6.2.4-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

  backend:
    image: ${{ secrets.DOCKER_HUB_USERNAME }}/con-to-dep:latest
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --no-input &&
      gunicorn config.wsgi --bind 0.0.0.0:8000 --workers 3"
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  web:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - django_static:/usr/share/nginx/html/static/
      - ./ssl:/etc/nginx/ssl

  celery-worker:
    image: ${APP_IMAGE}
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: celery -A config worker -l INFO

volumes:
  pg_data:
  django_static: